# Generated by Django 4.0.4 on 2022-05-14 14:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='project_category',
        ),
        migrations.AddField(
            model_name='account',
            name='account_manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='description',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('Computer', 'Computer'), ('Accessories', 'Acessories'), ('Printer', 'Printer'), ('Health', 'Health'), ('Web Apps', 'Web Apps'), ('Mobile Apps', 'Mobile Apps'), ('Desktop Apps', 'Desktop Apps'), ('Website', 'Website'), ('Graphic Design', 'Graphic Design'), ('Others', 'Others')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='customer',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='client_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
