# Generated by Django 4.0.4 on 2022-05-14 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_remove_project_project_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='description',
            new_name='comment',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='category',
            new_name='project_category',
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(max_length=300, null=True),
        ),
    ]
