# Generated by Django 4.0.4 on 2022-05-14 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_alter_product_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Computer', 'Computer'), ('Smart Phones', 'Smart Phones'), ('Tablet', 'Tablet'), ('Accessories', 'Acessories'), ('Printer', 'Printer'), ('Health', 'Health')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_category',
            field=models.CharField(choices=[('Web Apps', 'Web Apps'), ('Mobile Apps', 'Mobile Apps'), ('Desktop Apps', 'Desktop Apps'), ('Website', 'Website'), ('Graphic Design', 'Graphic Design'), ('Others', 'Others')], max_length=100, null=True),
        ),
    ]
