# Generated by Django 4.0.4 on 2022-05-26 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stdboard', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video_post',
            name='description',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
